

# the target is obtained linking all .o files
all: 
	make -f Makefile1 purge && make -f Makefile2 purge && make -f Makefile3 purge && make -f Makefile1 && make -f Makefile2 && make -f Makefile3
################################################################################
################################################################################
