

# the target is obtained linking all .o files
all: make1 make2 make3 make4 make5 make6

make1:
	make -f Makefile1

make2:
	make -f Makefile2

make3:
	make -f Makefile3

make4:
	make -f Makefile4

make5:
	make -f Makefile5

make6:
	make -f Makefile6	

purge: clean

clean:
	make -f Makefile1 purge && make -f Makefile2 purge && make -f Makefile3 purge  && make -f Makefile4 purge && make -f Makefile5 purge && make -f Makefile6 purge

###############################################################################
################################################################################
